version: 1.0.{build}
build_cloud: Hyper-V
image: Windows
configuration: Debug
platform: Any CPU
install:
- cmd: >-
    appveyor DownloadFile "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"

    msbuild "SafeExamBrowser.sln" /t:Restore
build_script:
- ps: .\build.ps1
artifacts:
- path: patch-seb/bin/Debug/patch-seb.exe
  name: Safe Exam Browser Patch